// ZzFX (sound effects) + SoundBox/voxby CPlayer (background music) share one
// AudioContext (zzfxX). Music helpers are at the bottom of this file.

// ZzFX Music's optimized copy of ZzFX by Frank Force https://github.com/KilledByAPixel/ZzFX

import { CPlayer } from './player';

// zzfxX - the common audio context
const zzfxX=new(window.AudioContext||webkitAudioContext);

// starting output level (0..1) - voxby/SoundBox has no volume knob of its
// own (a track plays at whatever the tracker's instrument volumes render to,
// scaled by the player's fixed internal gain), so this GainNode is the only
// lever; it was too loud at the GainNode's implicit 1.0 default. Also the
// (currently unused) ZzFX SFX's ceiling once that lands. Exported so game.js
// can seed the title menu's Music % label from the same number instead of
// duplicating it. The title menu's Music item / M key cycle the live level
// from here in 10-point steps, wrapping past 50% back to 0% - see
// cycleVolume() in game.js.
export const MASTER_VOLUME = 0.3;

// master gain every source (SFX + music) routes through, so setting it here
// scales the lot at once - including tracks/SFX that start after. Starts at
// MASTER_VOLUME (not the GainNode's 1.0 default) - setVolume() isn't called
// until the first M press/tap, and playback can start before that.
const zzfxMaster=zzfxX.createGain();
zzfxMaster.gain.value = MASTER_VOLUME;
zzfxMaster.connect(zzfxX.destination);

/** Set the master volume (0..1) for all game audio (music + SFX). */
export const setVolume = v => { zzfxMaster.gain.value = v; };

// zzfxV - global volume
const zzfxV=.3

// zzfxR - global sample rate
const zzfxR=44100

// zzfxP() - the sound player -- returns a AudioBufferSourceNode
const zzfxP=(...t)=>{let e=zzfxX.createBufferSource(),f=zzfxX.createBuffer(t.length,t[0].length,zzfxR);t.map((d,i)=>f.getChannelData(i).set(d)),e.buffer=f,e.connect(zzfxMaster),e.start();return e}

// zzfxG() - the sound generator -- returns an array of sample data. Ported
// straight from ZzFX v1.3.2 (https://github.com/KilledByAPixel/ZzFX,
// ZzFXMicro.min.js's generator half, split from its buffer/play half so
// zzfxP below can still route the result through zzfxMaster) - the version
// this used to be vendored from predated the tremolo/filter params (19 args,
// not 21), which silently mangled any sound exported from a current-gen ZzFX
// designer that sets a non-zero filter.
const zzfxG=(p=1,k=.05,b=220,e=0,r=0,t=.1,q=0,D=1,u=0,y=0,v=0,z=0,l=0,E=0,A=0,F=0,c=0,w=1,m=0,B=0,N=0,M=Math,d=2*M.PI,R=zzfxR,G=u*=500*d/R/R,C=b*=(1-k+2*k*M.random(k=[]))*d/R,g=0,H=0,a=0,n=1,I=0,J=0,f=0,h=N<0?-1:1,x=d*h*N*2/R,L=M.cos(x),Z=M.sin,K=Z(x)/4,O=1+K,X=-2*L/O,Y=(1-K)/O,P=(1+h*L)/2/O,Q=-(h+L)/O,S=P,T=0,U=0,V=0,W=0)=>{e=R*e+9;m*=R;r*=R;t*=R;c*=R;y*=500*d/R**3;A*=d/R;v*=d/R;z*=R;l=R*l|0;p*=zzfxV;for(h=e+m+r+t+c|0;a<h;k[a++]=f*p)++J%(100*F|0)||(f=q?1<q?2<q?3<q?4<q?(g/d%1<D/2)*2-1:Z(g**3):M.max(M.min(M.tan(g),1),-1):1-(2*g/d%2+2)%2:1-4*M.abs(M.round(g/d)-g/d):Z(g),f=(l?1-B+B*Z(d*a/l):1)*(4<q?f:(f<0?-1:1)*M.abs(f)**D)*(a<e?a/e:a<e+m?1-(a-e)/m*(1-w):a<e+m+r?w:a<h-c?(h-a-c)/t*w:0),f=c?f/2+(c>a?0:(a<h-c?1:(h-a)/c)*k[a-c|0]/2/p):f,N?f=W=S*T+Q*(T=U)+P*(U=f)-Y*V-X*(V=W):0),x=(b+=u+=y)*M.cos(A*H++),g+=x+x*E*Z(a**5),n&&++n>z&&(b+=v,C+=v,n=0),!l||++I%l||(b=C,u=G,n=n||1);return k};

// zzfx() - the universal entry point -- returns a AudioBufferSourceNode
const zzfx=(...t)=>zzfxP(zzfxG(...t))

// ZzFXM (v2.0.2) | (C) Keith Clark | MIT | https://github.com/keithclark/ZzFXM
const zzfxM=(f,n,o,t=125)=>{let z,e,l,r,g,h,x,a,u,c,d,i,m,p,G,M,R=[],b=[],j=[],k=0,q=1,s={},v=zzfxR/t*60>>2;for(;q;k++)R=[q=a=d=m=0],o.map((t,d)=>{for(x=n[t][k]||[0,0,0],q|=!!n[t][k],G=m+(n[t][0].length-2-!a)*v,e=2,r=m;e<x.length+(d==o.length-1);a=++e){for(g=x[e],u=c!=(x[0]||0)|g|0,l=0;l<v&&a;l++>v-99&&u?i+=(i<1)/99:0)h=(1-i)*R[p++]/2||0,b[r]=(b[r]||0)+h*M-h,j[r]=(j[r++]||0)+h*M+h;g&&(i=g%1,M=x[1]||0,(g|=0)&&(R=s[[c=x[p=0]||0,g]]=s[[c,g]]||(z=[...f[c]],z[2]*=2**((g-12)/12),zzfxG(...z))))}m=G});return[b,j]}


// Music wrapper API

/**
 * Generate ZzFX Music song data
 * @param {*} songs: array of song parameteres in ZzFX Music format https://github.com/keithclark/ZzFXM#song-format
 * @returns array of song data fit for ZzFX Music player
 */
export const loadSongs = songs => songs.map(song => zzfxM(...song));

/**
 * Play a ZzFX Music song
 * @param {*} songData song data generated by loadSongs/zzfxM
 * @returns an Audio Node to control the song playing (and stop if for example)
 */
export const playSong = songData => zzfxP(...songData);

/**
 * Play a ZzfX sound 
 * @param {*} soundData sound parameters in ZzFX format https://github.com/KilledByAPixel/ZzFX#zzfx-is-a-javascript-sound-effect-engine-and-creation-tool
 * @returns ?
 */
export const playSound = soundData => zzfx(...soundData);

// SFX data, straight out of the ZzFX sound designer's JSON export:
// [volume, randomness, frequency, attack, sustain, release, shape,
// shapeCurve, slide, deltaSlide, pitchJump, pitchJumpTime, repeatTime, noise,
// modulation, bitCrush, delay, sustainVolume, decay, tremolo, filter]
export const SFX_DIG = [1, 0.05, 178, 0.04, 0.03, 0.08, 1, 2.5, 2, 171, 0, 0, 0, 0.8, 0, 0.1, 0, 0.59, 0.05, 0, -1488];       // collecting a dust cell
export const SFX_TALLY = [1.8, 0.05, 523, 0.02, 0.09, 0.29, 0, 0.7, 0, 0, 307, 0.1, 0, 0.2, 0, 0.1, 0, 0.69, 0.01, 0, -1497]; // dust-counter tally-tick

// end-run rainbow sprouting: a low sine climbing steadily higher (positive
// slide, no deltaSlide so the rise stays linear), hand-tuned rather than
// exported from the designer. Baked at a nominal SFX_RAINBOW_DURATION - the
// caller (game.js) stretches playback via .playbackRate so it spans however
// long the rewind + rainbow grow actually take (that total isn't fixed, it
// scales with the shaft's length).
export const SFX_RAINBOW = [1, 0.02, 90, 0.05, 1.2, 1, 0, 1, 0.35, 0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0.3];
export const SFX_RAINBOW_DURATION = 2.55; // attack+decay+sustain+release above, in seconds


// --- Background music (voxby / SoundBox songs, played through player.js) ---

let musicSrc;                                   // the looping BufferSourceNode, or null

/**
 * Render a voxby-exported song to an AudioBuffer. Synchronous and blocking
 * (~40 ms per channel) - call at load time, cache the result.
 * @param {*} data the song's `export default {...}` object
 */
export const renderSong = data => {
  const p = new CPlayer();
  p.init(data);
  while (p.generate() < 1) { /* one pass per channel */ }
  return p.createAudioBuffer(zzfxX);
};

/** Loop `buffer` as the background track, stopping whatever was playing. */
export const playMusic = buffer => {
  stopMusic();
  musicSrc = zzfxX.createBufferSource();
  musicSrc.buffer = buffer;
  musicSrc.loop = true;
  musicSrc.connect(zzfxMaster);
  musicSrc.start();
};

export const stopMusic = () => {
  if (musicSrc) { try { musicSrc.stop(); } catch (e) {} musicSrc = null; }
};

// The context starts suspended (no autoplay without a gesture) and must be
// suspended again on tab-hide / pause or the loop keeps sounding. Safe to call
// unconditionally.
export const resumeAudio = () => { try { zzfxX.resume(); } catch (e) {} };
export const suspendAudio = () => { try { zzfxX.suspend(); } catch (e) {} };
